name: Appwrite Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Appwrite CLI
        shell: bash
        run: curl -sL https://appwrite.io/cli/install.sh | bash
      - name: Setup Appwrite CLI
        shell: bash
        run: |
          appwrite client \
            --endpoint='${{ secrets.APPWRITE_ENDPOINT }}' \
            --projectId='${{ secrets.APPWRITE_PROJECT_ID }}' \
            --key='${{ secrets.APPWRITE_API_KEY }}'
      - name: Init collection
        run: appwrite init collection --all
      - name: Deploy
        run: appwrite deploy collection --all --yes
