name: Appwrite Deploy
on: [push]

jobs:
  setup:
    name: Setup Appwrite
    runs-on: ubuntu-latest
    - uses: appwrite/setup-for-actions@v1
      with:
        endpoint: '${{ secrets.APPWRITE_ENDPOINT }}'
        project: '${{ secrets.APPWRITE_PROJECT_ID }}'
        key: '${{ secrets.APPWRITE_API_KEY }}'
  deploy:
    name: Deploy
    run: appwrite deploy collections --all --yes 
